#! /bin/sh
#  ____ _____ 
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |  	http://www.youtube.com/c/DistroTube
# | |_| || |  	http://www.gitlab.com/dwt1/ 
# |____/ |_|  	
#        
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### AUTOSTART ####
sxhkd &
picom -f &
############### set wallpaper   ######################
#exec --no-startup-id sleep 2 && nitrogen --restore
feh --bg-fill --randomize ~/.background/* &
~/.config/polybar/launch.sh &
kitty &
thunar &
Firefox-esr &

#### MONITORS ####
#bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
#bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor -d 1 2 3 4 5 6 7 8 9

#### BSPWM configuration ####
#bspc config border_radius                 0
bspc config border_width                  0
bspc config window_gap                    4
bspc config top_padding                   8
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      	"#4c566a"
bspc config active_border_color	          	"#1e1e1e"
bspc config focused_border_color	      	"#5e81ac"
bspc config presel_feedback_color	      	"#5e81ac"
bspc config urgent_border_color 	     	"#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)


bspc rule -a kitty desktop='^1' follow=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on
bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Firefox-esr desktop='^2' follow=on
bspc rule -a Pcmanfm desktop='^3' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a code-ess desktop='^4' follow=on
bspc rule -a Emacs desktop='^4' follow=on
bspc rule -a Code desktop='^4' follow=on
bspc rule -a Subl desktop='^4' follow=on
bspc rule -a VSCodium desktop='^4' follow=on
bspc rule -a Gedit desktop='^4' follow=on
bspc rule -a Notepadqq desktop='^4' follow=on
bspc rule -a libreoffice-writer desktop='^5' follow=on
bspc rule -a vlc desktop='^7' follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on

#==============  Floating  ================
bspc rule -a GParted state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Galculator state=floating
bspc rule -a File Transfer* state=floating
bspc rule -a Lightdm-gtk-greeter-settings state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Timeset-gui state=floating
bspc rule -a Xfburn state=floating
bspc rule -a TelegramDesktop state=floating
bspc rule -a Nm-connection-editor state=floating

bspc rule -a Screenkey manage=off
