# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                         # The name of the module we are configuring is "character"
success_symbol = "[ ::](bold green)"  # The "success_symbol" is set to "➜" with color "bold green"
error_symbol = "[ ::](bold red)" 		# used if previous command failed

# Use custom format
#format = """
#[|](bold green)
#[│](bold green)$directory$rust$package
#[└─::](bold green) """

# ~/.config/starship.toml

#[shell]
#fish_indicator = ""
#powershell_indicator = "_"
#unknown_indicator = "mystery shell"
#format = "[$indicator]($style) "
#style = "cyan bold"
#disabled = false


# Indicates when in bash shell.
#[custom.bash]
#command = "echo 🚀"
#when = '[ "$STARSHIP_SHELL" == "bash" ]'

# Indicates when in fish shell.
#[custom.fish]
#command = "echo " 
#when = 'test "$STARSHIP_SHELL" = "fish"'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname]($style):: "
trim_at = "-"
style = "bold dimmed white"
disabled = false

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = true

[time]
time_format = "%l:%M%P"
format = "$time($style) "
use_12hr = true
style = "bright-white"
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 3
format = "[$path]($style)[$lock_symbol]($lock_style) "

# ~/.config/starship.toml

[username]
style_user = "yellow bold"
style_root = "green bold"
format = "[$user]($style) "
disabled = true
show_always = true


